export class User {
  constructor(
    public id?: number,
    public login?: string,
    public password?: any,
    public firstName?: string,
    public lastName?: string,
    public telephone?: string,
    public email?: string,
    public fonction?: string,
    public specialite?: string,
    public numeroPiece?: string,
    public photo?: any,
    public photoContentType?: string,
    public facebook?: string,
    public twitter?: string,
    public linkedIn?: string,
    public whatsapp?: string,
    public createdBy?: string,
    public activated?: boolean,
    public activationKey?: string,
    public resetKey?: string,
    public resetDate?: any,
    public codeTelephone?: string,
    public lieuNaissance?: string,
    public dateNaissance?: string,
    public sexe?: string,
    public authorities?: string[],
  ) {}
}
